In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data1 = pd.read_csv('personal_health_data.csv')
data2 = pd.read_csv('digital_interaction_data.csv')
data3 = pd.read_csv('activity_environment_data.csv')

In [11]:
merge_df = pd.merge(data1, data2, on='User_ID', how='left')

In [12]:
final_df = pd.merge(merge_df, data3, on='User_ID', how='left')

In [13]:
final_df.head()

,User_ID,Age,Gender,Weight,Height,Medical_Conditions,Medication,Smoker,Alcohol_Consumption,Timestamp_x,...,Steps,Calories_Burned,Distance_Covered,Exercise_Type,Exercise_Duration,Exercise_Intensity,Ambient_Temperature,Battery_Level,Altitude,UV_Exposure
0,U_00001,61,Other,88.677623,178.524231,Diabetes,No,No,Moderate,2021-01-01 00:00:00,...,9146,457.30,7.3168,Running,1.219675,Low,27.271525,97.338777,1739.690662,4.069132
1,U_00002,24,Male,86.742084,200.346358,NaN,Yes,No,Moderate,2021-01-01 01:00:00,...,9362,468.10,7.4896,Yoga,1.378399,Moderate,24.430288,66.573240,4102.042824,1.723672
2,U_00003,81,Other,61.656054,195.971356,Hypertension,Yes,No,Moderate,2021-01-01 02:00:00,...,21,1.05,0.0168,Strength Training,0.803857,Moderate,29.340574,30.138828,1794.899935,0.135647
3,U_00004,70,Other,141.513794,164.178216,Hypertension,No,No,Heavy,2021-01-01 03:00:00,...,13252,662.60,10.6016,NaN,0.000000,NaN,25.289230,78.838640,4025.840921,4.408343
4,U_00005,30,Other,80.552872,146.920675,Diabetes,Yes,Yes,Heavy,2021-01-01 04:00:00,...,21,1.05,0.0168,Yoga,0.807389,High,21.853590,17.673261,3422.381447,2.820739

In [14]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User_ID                 10000 non-null  object
 1   Age                     10000 non-null  int64
 2   Gender                  10000 non-null  object
 3   Weight                  10000 non-null  float64
 4   Height                  10000 non-null  float64
 5   Medical_Conditions      6696 non-null   object
 6   Medication              10000 non-null  object
 7   Smoker                  10000 non-null  object
 8   Alcohol_Consumption     6640 non-null   object
 9   Timestamp_x             10000 non-null  object
 10  Day_of_Week             10000 non-null  object
 11  Sleep_Duration          10000 non-null  float64
 12  Deep_Sleep_Duration     10000 non-null  float64
 13  REM_Sleep_Duration      10000 non-null  float64
 14  Wakeups                 10000 non-null  int64
 15  Snoring                 10000 non-null  object
 16  Heart_Rate              10000 non-null  int64
 17  Blood_Oxygen_Level      10000 non-null  float64
 18  ECG                     10000 non-null  object
 19  Calories_Intake         10000 non-null  float64
 20  Water_Intake            10000 non-null  float64
 21  Stress_Level            10000 non-null  object
 22  Mood                    10000 non-null  object
 23  Skin_Temperature        10000 non-null  float64
 24  Body_Fat_Percentage     10000 non-null  float64
 25  Muscle_Mass             10000 non-null  float64
 26  Health_Score            10000 non-null  float64
 27  Anomaly_Flag            10000 non-null  int64
 28  Timestamp_y             10000 non-null  object
 29  Notifications_Received  10000 non-null  int64
 30  Screen_Time             10000 non-null  float64
 31  Timestamp               10000 non-null  object
 32  Steps                   10000 non-null  int64
 33  Calories_Burned         10000 non-null  float64
 34  Distance_Covered        10000 non-null  float64
 35  Exercise_Type           7399 non-null   object
 36  Exercise_Duration       10000 non-null  float64
 37  Exercise_Intensity      7399 non-null   object
 38  Ambient_Temperature     10000 non-null  float64
 39  Battery_Level           10000 non-null  float64
 40  Altitude                10000 non-null  float64
 41  UV_Exposure             10000 non-null  float64
dtypes: float64(20), int64(6), object(16)
memory usage: 3.2+ MB